### ISSUE TITLE
failed to use the pyzkfp library

### ISSUE THREAD

**Issue by IsaacMjr** [alqasemy2020/pyzkfp#1]
hello thank you for the pyzkfp library but I am facing a few issues. When I tried using the library i get this error --Failed to create a default .NET runtime, which would
                    have been "mono" on this system. Either install a
                    compatible runtime or configure it explicitly via
                    `set_runtime` or the `PYTHONNET_*` environment variables
                    (see set_runtime_from_env)--
Am I supposed to first install some dependencies before installing **pyzkfp** if so please state them in the documentation. Am running python 3.11
thank you

**Comment by aqasemi** [comment]
yeah my bad, i didn't mention this in the readme file, but you have to install Mono or any other .NET runtime if you're using an OS other than windows.

**Comment by IsaacMjr** [comment]
i am running linux zorin, maybe you can include a full step by step guide in the readme file
 because I am having challenges installing other dependencies

**Comment by aqasemi** [comment]
will do. but in the meantime, you can check out this [quick tutorial](https://www.mono-project.com/download/stable/#download-lin) on how to install Mono. 
After that make sure you install the right ZK SDK (Linux version; link in readme file).
