### ISSUE TITLE
DBmatch not working for me

### ISSUE THREAD

**Issue by zubochistka1337** [alqasemy2020/pyzkfp#2]
Hi! I have a zk9500 device and I work with python, so I came across your library. I need to save my fingerprints in the database and get them back. I register the fingerprint through **DBmerge** and put it in my database (for emulation, I just use writing bytes next to it in a file). Next, I want to compare the fingerprint in the database with the attached finger and the **DBmatch** function shows that the fingerprint in the database does not match the attached one. I am attaching a simple code of my actions for understanding. What am I doing wrong? [simple_example](https://pastebin.com/CmRKymQj)

**Comment by aqasemi** [comment]
`DBMatch` is used to compare two fingerprints. You used it to compare a fingerprint and a result of merging three fingerprints `python_bytes`.

that said, `DBMatch` is used just to make sure a user enters the same fingerprint n times by matching each fingerprint with the latter. i.e., you may do something like `DBMatch(templates[0], templates[1])`

please refer to the documentation for more info or have a look at this [example](https://github.com/alqasemy2020/pyzkfp/blob/main/examples/example.py).
