### ISSUE TITLE
DBmatch returning something like score, not 1 or 0

### ISSUE THREAD

**Issue by zubochistka1337** [alqasemy2020/pyzkfp#3]
Hi, I spent a lot of time to understand why my application does not recognize my finger through DBmatch, it turned out that DBmatch does not return **1 or 0**. But something similar to the comparison **score from 0 to 1000**, as I understood. But this score behaves quite **randomly** and sometimes gives out **300**, sometimes **800**, if i apply the same finger in the same way

**Comment by aqasemi** [comment]
Hi there, thanks for opening this issue. 

I've built two private projects using this library, and the way i use `DBmatch` is by just checking whether the result is above zero or not. So far, I've not faced any problems by doing so. Additionally, no matter how many times i try i cannot get it to give a score more than 0 for different fingers. Thus, i think just checking if the matching result is above zero should be fine.
