### ISSUE TITLE
Storing data

### ISSUE THREAD

**Issue by SantiSarGon** [alqasemy2020/pyzkfp#4]
Hello! sorry to ask but could you help me on how to store the regtemp data for later use? I am having issues on how handle it.

Thanks in advance!

**Comment by aqasemi** [comment]
Hi there. Can you provide me with the code you used to save it? 

I would store the object as it as retuned from the `DBMerge` (`Array[Byte]` type; without casting) in a BLOB column in a database.

**Comment by SantiSarGon** [comment]
Hi, thank you for the quick response!!
Ohhh I see, there was my issue. For the moment I want to store it locally.

I have finally managed to get the result I wanted.
At the moment I am saving it to a JSON file, I am storing an array with the id and the data, for the data I have to convert the binary array, I am using the following line
base64_encoded_data = base64.b64encode(byte_data).decode('utf-8')

Finally in order to add it back when first loading I just read the JSON and decode/encode the data again
zkfp2.DBAdd(data['id'], bytearray(base64.b64decode(data['byte_data'])))

I will probably migrate to the DB approach soon. I wanted to leave this here in case it helps someone who wants to store it locally in a file such as JSON.

**Comment by aqasemi** [comment]
Thanks for sharing your approach. I'm closing this issue now.
