### ISSUE TITLE
Image display

### ISSUE THREAD

**Issue by SantiSarGon** [alqasemy2020/pyzkfp#5]
Hello!
I am trying to use the img obtained after the capture whih is a bytes object. But I can't manage to transform it into an image. I am trying with io.BytesIO and keep getting the following error.
UnidentifiedImageError: cannot identify image file

If you can help me with this I would appreciate it enormously.

Thank you in advance!

**Comment by aqasemi** [comment]
There's a method [show_image](https://github.com/alqasemy2020/pyzkfp/blob/a89f769bfe4cd3c59478654300e07580cdac5fec/pyzkfp/zkfp2.py#L462) which takes the img buffer obtained from the device and displays it. You can look its definition for more details.

**Comment by SantiSarGon** [comment]
Yes the definition did helped a lot, again, thank you very much!
