### ISSUE TITLE
Code to identify finger prints ?

### ISSUE THREAD

**Issue by nmeyen** [alqasemy2020/pyzkfp#6]
First of all great work ! Do you have any code samples to idenitfy existing fingerprints and validate against them ?

**Comment by aqasemi** [comment]
Thank you. You can look up the documentation in the Readme file. I've also included a simple implementation in the `examples` directory. If you still have any questions, feel free to ask.

**Comment by nmeyen** [comment]
@alqasemy2020 thank you very much will check it out
