### ISSUE TITLE
Odoo integrate fingerprint scanner ZK9500

### ISSUE THREAD

**Issue by BatohaShir** [alqasemy2020/pyzkfp#8]
Hello esteemed developer,

I am integrating a fingerprint scanner with Odoo 16. Since Odoo 16 itself cannot interact directly with the fingerprint scanner, I have decided to implement a Flask application that listens to HTTP requests. In the scenario where I want to compare two fingerprints, one fingerprint is captured from the scanner, while the other is received along with an HTTP request in base64 format. However, when I start comparing them, I always receive a message that the fingerprints do not match. Here is my code:

@app.route('/identify', methods=['POST'])
def identify():
    try:
        device_count = zkfp2.GetDeviceCount()
        if device_count > 0:
            zkfp2.OpenDevice(0)
            start_time = time.time()
            while True:
                zkfp2.Light('green')
                time.sleep(0.09)
                capture = zkfp2.AcquireFingerprint()
                if capture:
                    fingerprint_captured_template = capture[0]
                    data = request.json
                    fingerprint_to_compare_base64 = data.get('fingerprint_base64')
                    fingerprint_to_compare = base64.b64decode(fingerprint_to_compare_base64)
                    match_score = zkfp2.DBMatch(fingerprint_captured_template, fingerprint_to_compare)
                    if match_score > 0:
                        return jsonify({"message": "Fingerprint matched", "score": match_score})
                    else:
                        return jsonify({"message": "Fingerprint did not match", "score": match_score})
                    break
                if time.time() - start_time > 10:
                    zkfp2.CloseDevice()
                    return jsonify({"message": "Fingerprint scanning timeout"})
                    break
            zkfp2.CloseDevice()
        else:
            return jsonify({"message": "No device found"}), 500
    except Exception as e:
        return jsonify({"message": str(e)}), 500
Could you please advise on how to properly compare them and why my comparison is not working correctly?

**Comment by aqasemi** [comment]
i guess it's not working with you because you apparently didn't initialize the zkfp2 class (`zkfp2.Init()`) before generally interacting with the library's functions. 

i tried this and it worked as intended:
```
app = Flask(__name__)
zkfp2 = ZKFP2()

# write temp to file to use it when sending the reqeust
# while True:
#     capture = zkfp2.AcquireFingerprint()
#     if capture:
#         with open('fingerprint', 'w') as f:
#             f.write(b64encode(bytes(capture[0])).decode())
#         break


@app.route('/identify', methods=['POST'])
def identify():
    zkfp2.Init()
    device_count = zkfp2.GetDeviceCount()
    zkfp2.OpenDevice(0)
    zkfp2.Light('green')
    if device_count > 0:
        start_time = time.time()
        while True:
            zkfp2.Light('green')
            time.sleep(0.09)
            capture = zkfp2.AcquireFingerprint()
            if capture:
                fingerprint_captured_template = capture[0]
                data = request.json
                fingerprint_to_compare_base64 = data.get('fingerprint_base64')
                fingerprint_to_compare = b64decode(fingerprint_to_compare_base64)
                match_score = zkfp2.DBMatch(fingerprint_captured_template, fingerprint_to_compare)
                
                print(match_score)

                if match_score > 0:
                    return jsonify({"message": "Fingerprint matched", "score": match_score})
                else:
                    return jsonify({"message": "Fingerprint did not match", "score": match_score})
                
            if time.time() - start_time > 10:
                zkfp2.CloseDevice()
                return jsonify({"message": "Fingerprint scanning timeout"})
    else:
        return jsonify({"message": "No device found"}), 500
```

i don't know of the context, but you should keep in mind that you're doing a `1:1` comparison.

**Comment by aqasemi** [comment]
also note i am missing a lot of context here. so it might not be the case that what is causing the problem in your side is the `zkfp2.Init`.
