### ISSUE TITLE
work with external databases

### ISSUE THREAD

**Issue by JurabekUz** [alqasemy2020/pyzkfp#9]
Hello dear developer

How can I use this library in external databases like PostgreSql, SQLite? I am going to save the temp and identify it in an external database. Could you give me an example?

**Comment by aqasemi** [comment]
Hi there. 

If I understood correctly, you want to save fingerprints templates in an external database and use them later on? If that's the case, then you can refer to the [readme file](https://github.com/alqasemy2020/pyzkfp?tab=readme-ov-file#storing-and-loading-templates-from-an-external-database-for-future-use). But generally, you would want to either save the final template of a fingerprint as a Blob type in your database or as base64 string and decode it back when needed.

However, if that's not the case, then kindly elaborate more.
